dist: xenial

language: python

matrix:
  include:
    - python: 3.7
    - python: 3.8
      PYTEST_MYPY=--mypy
    - python: 3.9-dev

install:
  - pip install .[dev]

script:
  - py.test -vvv $PYTEST_MYPY
