dist: xenial

language: python

matrix:
  include:
    - python: 3.7
    - python: 3.8
      env: PRE_COMMIT=true PYTEST_MYPY=--mypy
    - python: 3.9-dev

install:
  - pip install .[dev]

script:
  - py.test -vvv $PYTEST_MYPY
  - if [[ $PRE_COMMIT ]]; then pre-commit install; pre-commit run --all-files; fi
