[build-system]
requires = [
  'setuptools >= 42',
  'wheel',
]

[tool.isort]
# These settings ensure that black and isort don't disagree on the imports.
line_length = 88
multi_line_output = 3
include_trailing_comma = true

known_third_party = ['iscsi', 'sgio']
